Реализовать контролеры для фильмов и пользователй
filin155/java-filmorate pull request #5
Opened 2024-03-11 13:21 UTC by filin155

Добавлены два контролера для создания и редактирования пользователей и фильмов + тесты к ним

2024-03-11 15:40 UTC, Yang-Pi requested changes

2024-03-11 15:40 UTC, Yang-Pi commented on pom.xml
> +		<dependency>
Это ненужная для проекта зависимость

2024-03-11 15:40 UTC, Yang-Pi commented on pom.xml
> +		<dependency>
Тоже нужно убрать

2024-03-11 15:40 UTC, Yang-Pi commented on pom.xml
> +		<dependency>
И эту

2024-03-11 15:40 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private String name;
Все же рекомендую перейти на валидацию на уровне модели) в рамках этого спринта можно и так, но дальше будет проще, да и на самом деле правильнее, именно с моделью

2024-03-12 05:56 UTC, filin155 commented on pom.xml
> +		<dependency>
удалил

2024-03-12 05:56 UTC, filin155 commented on pom.xml
> +		<dependency>
удалил

2024-03-12 05:56 UTC, filin155 commented on pom.xml
> +		<dependency>
удалил

2024-03-14 19:09 UTC, Yang-Pi approved these changes

2024-03-15 15:15 UTC, merged